version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
    environment:
      MONGO_DATABASE: mongodb://mongodb:27017/locationdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      PORT: 4000
      JWT_SECRET: ${JWT_SECRET:-changeme}
      CITIES_DATA_FROM_IBGE: https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: